version: "3.8"

services:
  php_app:
    image: easyautomates/cbackend:latest  # Usa tu imagen aquí
    networks:
      - mononet

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.cuenty.rule=Host(`cbackend.easyautomates.com`)
        - traefik.http.services.cuenty.loadbalancer.server.port=80
        - traefik.http.routers.cuenty.service=cuenty
        - traefik.http.routers.cuenty.tls.certresolver=letsencryptresolver
        - traefik.http.routers.cuenty.entrypoints=websecure
        - traefik.http.routers.cuenty.tls=true

networks:
  mononet:
    external: true
